sonar.projectKey=biblioteca-frontend
sonar.projectName=biblioteca-frontend
sonar.host.url=http://localhost:9000
sonar.login=sqp_a658d3fa44e3d3fbb03471db8b617847464bc2c8

# EXCLUSIONES CRÍTICAS
# Excluimos la carpeta coverage del análisis para que no cuente como código sin probar
sonar.sources=src
sonar.exclusions=src/coverage/**, **/*.spec.ts, node_modules/**, src/test-setup.ts

# CONFIGURACIÓN DE PRUEBAS
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# SOLUCIÓN AL ERROR DE TYPESCRIPT
# Esto obliga a Sonar a analizar los archivos aunque falle el programa de TS
sonar.typescript.tsconfigPath=tsconfig.json
sonar.lang.optimisticAnalysis=true